name: "📚 Documentation Builder"

on:
  push:
    branches: [ master ]
    paths:
      - 'docs/**/*'
      - '.github/workflows/docs_builder.yml'
      - 'requirements/documentation.txt'
      - 'roof_classify/**/*.py'
    tags: "*"

env:
  PYTHON_VERSION: 3.7

jobs:
  build-docs:

    runs-on: ubuntu-20.04

    steps:
    - name: Get source code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Cache project dependencies (pip)
      uses: actions/cache@v2.1.6
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install project requirements
      run: |
        python -m pip install -U pip setuptools wheel
        python -m pip install -U -r requirements/documentation.txt

    - name: Build doc using Sphinx
      run: sphinx-build -b html docs docs/_build/html

    - name: Deploy to GitHub Pages
      run: |
        python -m pip install -U ghp-import
        ghp-import --force --no-history --no-jekyll --push docs/_build/html
