name: "🚀 Releaser"

on:
  push:
    tags: "*"

env:
  PROJECT_FOLDER: "roof_classify"
  PYTHON_VERSION: 3.7

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Get source code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - uses: actions/cache@v2.1.7
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install system requirements
      run: |
        sudo apt update
        sudo apt install qt5-default qttools5-dev-tools

    - name: Install Python requirements
      run: |
        python -m pip install -U pip setuptools wheel
        python -m pip install -U -r requirements/packaging.txt
        python -m pip install --no-deps -U -r requirements/embedded.txt -t roof_classify/embedded_external_libs

    - name: Compile translations
      run: lrelease roof_classify/resources/i18n/*.ts

    - name : Get current changelog for ${GITHUB_REF/refs\/tags\//}
      run: qgis-plugin-ci changelog ${GITHUB_REF/refs\/tags\//} >> release.md

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body_path: release.md

    - name: Deploy plugin
      run: >-
        qgis-plugin-ci
        release ${GITHUB_REF/refs\/tags\//}
        --github-token ${{ secrets.GITHUB_TOKEN }}
        --allow-uncommitted-changes
        --create-plugin-repo
