name: "🎳 Tester"

on:
  push:
    branches: [master]
    paths:
      - "**.py"
      - 'requirements/embedded.txt'

  pull_request:
    branches: [master]
    paths:
      - "**.py"
      - 'requirements/embedded.txt'

env:
  PROJECT_FOLDER: "RoofClassify"
  PYTHON_VERSION: 3.9

jobs:
  tests:
    runs-on: ubuntu-latest

    container:
      image: qgis/qgis:release-3_16
      env:
        DISPLAY: ":99"
      options: -v ${{ github.workspace }}:/tests_directory

    steps:
      - name: Get source code
        uses: actions/checkout@v3

      - name: Print QGIS version
        run: qgis --version

      - uses: actions/cache@v3.0.4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python requirements
        run: |
          python3 -m pip install -U pip setuptools wheel
          python3 -m pip install --no-deps -U -r requirements/embedded.txt -t RoofClassify/embedded_external_libs
          python3 -m pip install -U -r requirements/testing.txt

      - name: Run Unit tests
        run: pytest
